### PR TITLE
Add MRR to ranking metrics module

### PR DESCRIPTION
**Pull request by murphp15**
Fixes https://github.com/NVIDIA-Merlin/Transformers4Rec/issues/86

### Goals :soccer:
Add support for mean reciprocal rank

### Implementation Details :construction:
I followed the template of NDCG to implement this. 

### Testing Details :mag:
Single basic unit test.

### CODE REVIEW

**Comment by murphp15** [comment]
I see that this is failing but I don't think it is related to my changes. Can you guys confirm?

**Comment by sararb** [comment]
Thank you for your PR @murphp15! It seems the unit tests are failing because of formatting problem. 
Could you please run the following commands under the main directory of transformers4rec to format your code and then commit your changes?
```
black .
isort .
flake8 .
```
you might need to download each of the respective packages using pip `pip install black isort flake8`

**Comment by murphp15** [comment]
@sararb  Done.

**Comment by albert17** [comment]
rerun tests

**Comment by albert17** [comment]
rerun tests

**Comment by murphp15** [comment]
@albert17 Is this an issue with my code or with your CI?

**Comment by albert17** [comment]
rerun tests

**Comment by albert17** [comment]
rerun tests

**Comment by murphp15** [comment]
@albert17  still failing

**Comment by albert17** [comment]
@murphp15 You are right. Let me merge #366 first. Your PR is failing becuase of the CI system

**Comment by albert17** [comment]
@murphp15 it should run fine now

**Comment by albert17** [comment]
@rnyak @gabrielspmoreira @sararb This PR passes testing now.

@murphp15 sorry for taking so long to get this.

**Pull request merged**
