### PR TITLE
Fixes the OOM error when running all unit tests in CI env and GPU enabled machine

### PR DESCRIPTION
**Pull request by gabrielspmoreira**
Configures TF to enable memory growth for unit testing, so that it does not reserve all GPU memory and pytorch tests get OOM errors

### CODE REVIEW

**Review by sararb — APPROVED** [review]

**Comment by albert17** [comment]
@gabrielspmoreira Modify the CI testing script in this PR to run all the tests instead of only the TF ones.

Here: https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/ci/build_and_test.sh#L27 

Change from: 
  - `py.test --cov-config tests/.coveragerc --cov-report term-missing --cov-report xml --cov=. tests/tf`
To: 
 -  `py.test --cov-config tests/.coveragerc --cov-report term-missing --cov-report xml --cov=. tests`

**Comment by gabrielspmoreira** [comment]
@albert17 just included the pytorch tests in the CI script, as you suggested. Can you try it in the GPU-enabled CI env?

**Comment by albert17** [comment]
CI looking better, only getting 2 errors 
```
FAILED tests/torch/test_trainer.py::test_set_train_eval_loaders_pyarrow[16]
FAILED tests/torch/test_trainer.py::test_set_train_eval_loaders_pyarrow[32]
```

```
        )
    
>       assert resys_trainer.get_train_dataloader().batch_size == batch_size

tests/torch/test_trainer.py:77: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
transformers4rec/torch/trainer.py:143: in get_train_dataloader
    return T4RecDataLoader.parse(self.args.data_loader_engine).from_schema(
transformers4rec/torch/utils/data_utils.py:53: in parse
    return dataloader_registry.parse(class_or_str)
merlin_standard_lib/registry.py:265: in parse
    return self[class_or_str]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <merlin_standard_lib.registry.Registry object at 0x7fe81c38e640>
key = 'pyarrow'

    def __getitem__(self, key):
        if key not in self:
>           raise KeyError(
                "%s never registered with registry %s. Available:\n %s"
                % (key, self.name, display_list_by_prefix(sorted(self), 4))
            )
E           KeyError: 'pyarrow never registered with registry torch.dataloader_loader. Available:\n '

merlin_standard_lib/registry.py:232: KeyError
```

**Comment by sararb** [comment]
Thanks @gabrielspmoreira for the PR! And @albert17  for reporting the remaining issue. 

I suspect, it is due to missing `pyarrow` dependency in the CI env. You can see [here](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/3ad1e07382f323356a027962ed58965752552fb5/transformers4rec/torch/utils/data_utils.py#L56) that the class is registered only when `pyarrow` is available. 

@albert17 Could you please check if the `pyarrow` is installed?

( if it is the case, I think we should raise an error, to the user, explaining the dependency is missing)

**Comment by albert17** [comment]
@sararb I already checked the CI environment and it has pyarrow installed. 
```
$ docker run --runtime=nvidia --rm -it -p 9899:8888 -p 9897:8787 -p 9896:8786 --ip=host --cap-add SYS_PTRACE nvcr.io/nvstaging/merlin/merlin_ci_runner  /bin/bash
root@7f1e3cf86570:/opt/tritonserver# python
Python 3.8.10 (default, Jun  2 2021, 10:49:15)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow
>>> pyarrow.__version__
'4.0.1'
```

**Comment by gabrielspmoreira** [comment]
@albert17 Can you try running `import pyarrow.parquet as pq` on that CI instance, to check if this line is working with you pyarrow version?

**Comment by albert17** [comment]
@gabrielspmoreira @sararb No problem importing parquet from pyarrow
```
root@c396cfa3ad55:/opt/tritonserver# python
Python 3.8.10 (default, Jun  2 2021, 10:49:15)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow
>>> pyarrow.__version__
'4.0.1'
>>> import pyarrow.parquet as pq
>>>
```

**Comment by gabrielspmoreira** [comment]
@albert17 I was able to reproduce the issue with on the `test_set_train_eval_loaders_pyarrow` (`tests/torch/test_trainer.py`) on my workstation.

I ran the following commands for that:
```python
docker run --rm --gpus all -it nvcr.io/nvidia/merlin/merlin-pytorch-training:21.11
cd /transformers4rec
git pull origin main
pip install --user -e .[tensorflow,pytorch,nvtabular]
pytest tests/torch/test_trainer.py
```
Then I got this error on `test_set_train_eval_loaders_pyarrow` test
``'KeyError: 'pyarrow never registered with registry torch.dataloader_loader.``

I tried to import pyarrow on  `python` console and got a more informative error, saying that the issue is related to numpy install:
```python
python
Python 3.8.12 | packaged by conda-forge | (default, Sep 29 2021, 19:52:28) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow.parquet as pq
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/pyarrow/__init__.py", line 63, in <module>
    import pyarrow.lib as _lib
  File "pyarrow/lib.pyx", line 36, in init pyarrow.lib
ImportError: numpy.core.multiarray failed to import
```

Then, followed @benfred suggestion of running `pip install numpy==1.20` and then the issue is gone, and the tests run without issue.

P.s. When I run `pip install --user -e .` or `pip install --user -e .[pytorch,nvtabular]` without `tensorflow` instead of `pip install --user -e .[tensorflow,pytorch,nvtabular]` the error does not occur. The issue seems to be that when installing `tensorflow` in this Merlin Pytorch image 9`nvcr.io/nvidia/merlin/merlin-pytorch-training:21.11`) the `numpy` is downgraded to `1.19.5`, which seems to be imcompatible with latest `pyarrow`.

@benfred @albert17 Should we add `pip install numpy==1.20` after `pip install --user -e .[tensorflow,pytorch,nvtabular]` in [build_and_test.sh](https://github.com/NVIDIA-Merlin/Transformers4Rec/blob/main/ci/build_and_test.sh)?

**Comment by albert17** [comment]
@gabrielspmoreira Great, thanks for finding this.

I would try to avoid transferring infrastructure problems to software development domain.

For now, I can add the install in the CI system before running the script. 

For future, I will add the install to the containers at the end.

**Comment by albert17** [comment]
@benfred @gabrielspmoreira

Actually installing numpy before tf4rec does not work, because tf4rec downgrades it. It has to be installed after it.

So I guess we can 1) Add the numpy install in the script as Gabriel proposed; 2) I can edit the script on the CI side to add the numpy install.

I prefer option 1) as Gabriel suggested.

**Comment by gabrielspmoreira** [comment]
Thanks @albert17 . I will trust on @benfred and you to decide that :)

**Comment by albert17** [comment]
I discussed with @benfred  yesterday and it is better to add the numpy install in the `build_and_test.sh` script

@gabrielspmoreira please add it when possible

**Comment by albert17** [comment]
rerun tests

**Pull request merged**
